In [1]:
import numpy as np

### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [493]:
zp = np.array([[35, 45, 190, 200, 40, 70, 54, 150, 120, 110]])
ks = np.array([[401, 574, 874, 919, 459, 739, 653, 902, 746, 832]])

X = zp.reshape((10,1))
y = ks.reshape((10,1))
X, y

(array([[ 35],
        [ 45],
        [190],
        [200],
        [ 40],
        [ 70],
        [ 54],
        [150],
        [120],
        [110]]),
 array([[401],
        [574],
        [874],
        [919],
        [459],
        [739],
        [653],
        [902],
        [746],
        [832]]))

In [494]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@y)
B

array([[5.88982042]])

In [495]:
B1 = B[0,0]
y_hat = B1 * zp[0]
y_hat

array([ 206.1437147 ,  265.04191891, 1119.06587983, 1177.96408403,
        235.59281681,  412.28742941,  318.05030269,  883.47306302,
        706.77845042,  647.88024621])

In [496]:
mse = ((ks[0] - y_hat)**2).sum()/len(zp[0])
mse

56516.8584157194

In [497]:
X = np.hstack([np.ones((10,1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [498]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@y)
B

array([[444.17735732],
       [  2.62053888]])

In [499]:
B0 = B[0,0]
B1 = B[1,0]
y_hat = B0 + B1 * zp[0]
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [500]:
mse = ((ks[0] - y_hat)**2).sum()/len(zp[0])
mse

6470.414201176659

### 2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [556]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [557]:
def mse_(B1, X=X, y=y, n=10):
    return np.sum((B1*X - y)**2)/n

def for_cycle(b, alpha, m, n, X=X, y=y):
    for i in range(m):
        b -= alpha*(2/n) * np.sum((b * X - y) * X)
        if i % 1000 == 0 and m <= 100000:
            print(f'B1 = {b}, mse = {mse_(b)}')
        elif i % 100 == 0 and m <= 1000:
            print(f'B1 = {b}, mse = {mse_(b)}')
        elif i % 10 == 0 and m <= 100:
            print(f'B1 = {b}, mse = {mse_(b)}')
        elif m <= 10:
            print(f'B1 = {b}, mse = {mse_(b)}')

In [558]:
alpha = 1e-6

In [559]:
B1 = 6

In [560]:
n = 10

In [561]:
for_cycle(B1, alpha, 10, n)

B1 = 5.9969642, mse = 56675.010884630334
B1 = 5.99401204600456, mse = 56666.415737423886
B1 = 5.991141233298587, mse = 56658.28771258365
B1 = 5.9883495206692645, mse = 56650.601423307075
B1 = 5.98563472865636, mse = 56643.332862493815
B1 = 5.9829947378507455, mse = 56636.45932776262
B1 = 5.980427487239797, mse = 56629.959350543715
B1 = 5.977930972598381, mse = 56623.81262902432
B1 = 5.975503244924184, mse = 56617.9999647388
B1 = 5.9731424089161385, mse = 56612.503202604785


In [562]:
for_cycle(B1, alpha, 100, n)

B1 = 5.9969642, mse = 56675.010884630334
B1 = 5.970846621494791, mse = 56607.305174218185
B1 = 5.951095515292692, mse = 56568.58455176568
B1 = 5.936158977583853, mse = 56546.44038410262
B1 = 5.924863399683319, mse = 56533.776224013534
B1 = 5.916321254067367, mse = 56526.53364198457
B1 = 5.909861358667003, mse = 56522.391638560955
B1 = 5.904976140074413, mse = 56520.02284352452
B1 = 5.901281751973945, mse = 56518.66813920615
B1 = 5.898487915182776, mse = 56517.893389275516


In [563]:
for_cycle(B1, alpha, 4000, n)

B1 = 5.9969642, mse = 56675.010884630334
B1 = 5.889820420132767, mse = 56516.8584157194
B1 = 5.889820420132705, mse = 56516.8584157194
B1 = 5.889820420132705, mse = 56516.8584157194


In [564]:
mse_(5.8898)

56516.858421464

### 3. В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

таблица значений функции Лапласа используется когда нам дана сигма

таблица критических точек распределения Стьюдента используется когда неизвестна сигма

### *4. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [637]:
X = zp.reshape((10,1))
y = ks.reshape((10,1))
X, y

(array([[ 35],
        [ 45],
        [190],
        [200],
        [ 40],
        [ 70],
        [ 54],
        [150],
        [120],
        [110]]),
 array([[401],
        [574],
        [874],
        [919],
        [459],
        [739],
        [653],
        [902],
        [746],
        [832]]))

In [662]:
def mse_with_intercept(b_0, b_1, n, X=X, y=y):
    return np.sum((b_0 + b_1*X - y)**2)/n

def calc_b0_b1(b_0, b_1, alpha, m, n, X=X, y=y):
    
    for i in range(m):
        
        a = b_0 - alpha * (2/n) * np.sum(b_0 + b_1 * X - y)
        b = b_1 - alpha * (2/n) * np.sum((b_0 + b_1 * X - y) * X)
        
        b_0, b_1 = a, b
        
        if i % 1000 == 0 and m <= 100000:
            print(f'B0 = {b_0}, B1 = {b_1}, mse = {mse_with_intercept(b_0, b_1, n)}')
        elif i % 100 == 0 and m <= 1000:
            print(f'B0 = {b_0}, B1 = {b_1}, mse = {mse_with_intercept(b_0, b_1, n)}')
        elif i % 10 == 0 and m <= 100:
            print(f'B0 = {b_0}, B1 = {b_1}, mse = {mse_with_intercept(b_0, b_1, n)}')
        elif m <= 10:
            print(f'B0 = {b_0}, B1 = {b_1}, mse = {mse_with_intercept(b_0, b_1, n)}')

In [663]:
alpha = 1e-6

In [664]:
B0 = 444
B1 = 0.1

In [665]:
n = 10

In [666]:
calc_b0_b1(B0, B1, alpha, 10, n)

B0 = 444.00051152, B1 = 0.16948488, mse = 89323.55847833301
B0 = 444.00100894744327, B1 = 0.23705512546812801, mse = 84820.48013539784
B0 = 444.0014926706459, B1 = 0.3027634935705381, mse = 80562.14466015899
B0 = 444.0019630672241, B1 = 0.36666128776588336, mse = 76535.25024733422
B0 = 444.0024205043888, B1 = 0.42879839786177937, mse = 72727.21804641192
B0 = 444.0028653392327, B1 = 0.4892233389675241, mse = 69126.15286896935
B0 = 444.0032979190089, B1 = 0.5479832893734877, mse = 65720.80603155323
B0 = 444.003718581402, B1 = 0.6051241273867471, mse = 62500.54021805422
B0 = 444.0041276547918, B1 = 0.6606904671517263, mse = 59455.29625181582
B0 = 444.0045254585097, B1 = 0.7147256934838095, mse = 56575.561673683194


In [667]:
calc_b0_b1(B0, B1, alpha, 100, n)

B0 = 444.00051152, B1 = 0.16948488, mse = 89323.55847833301
B0 = 444.00491230308813, B1 = 0.7672719957431257, mse = 53852.34102783905
B0 = 444.00824048792475, B1 = 1.219334407832404, mse = 33567.11773037001
B0 = 444.0107575456189, B1 = 1.561195948222588, mse = 21966.43656393121
B0 = 444.01266120753286, B1 = 1.8197206773601846, mse = 15332.257508953746
B0 = 444.0141010033478, B1 = 2.0152239076414684, mse = 11538.313765290757
B0 = 444.0151900113599, B1 = 2.1630686151355265, mse = 9368.639264365283
B0 = 444.0160137443649, B1 = 2.2748726883146357, mse = 8127.849269027526
B0 = 444.0166368693985, B1 = 2.3594218814458894, mse = 7418.268264181235
B0 = 444.0171082893821, B1 = 2.4233602140708737, mse = 7012.474210114599


In [668]:
calc_b0_b1(B0, B1, alpha, 4000, n)

B0 = 444.00051152, B1 = 0.16948488, mse = 89323.55847833301
B0 = 444.01864150145354, B1 = 2.6217071010298523, mse = 6470.420591176474
B0 = 444.0187219979621, B1 = 2.621706508541758, mse = 6470.420584696434
B0 = 444.0188024536448, B1 = 2.6217059163523615, mse = 6470.420578222968
